# Generated by Django 4.0 on 2021-12-19 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('s', 'Sport'), ('b', 'Biblioteka'), ('g', 'Strona główna')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=75)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('subject', models.CharField(choices=[('pol', 'Język Polski'), ('ang', 'Język Angielski'), ('fra', 'Język Francuski'), ('nie', 'Język Niemiecki'), ('hiw', 'Historia i Wiedza o Społeczeństwie'), ('mat', 'Matematyka'), ('fiz', 'Fizyka'), ('che', 'Chemia'), ('bio', 'Biologia'), ('geo', 'Geografia'), ('inf', 'Informatyka'), ('edb', 'Edukacja dla bezpieczeństwa'), ('prz', 'Wiedza o przedsiębiorczości'), ('w-f', 'Wychowanie Fizyczne'), ('rel', 'Religia / Etyka'), ('ped', 'Pedagog'), ('bib', 'Biblioteka'), ('fil', 'Filozofia')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('pol', 'Język Polski'), ('ang', 'Język Angielski'), ('fra', 'Język Francuski'), ('nie', 'Język Niemiecki'), ('hiw', 'Historia i Wiedza o Społeczeństwie'), ('mat', 'Matematyka'), ('fiz', 'Fizyka'), ('che', 'Chemia'), ('bio', 'Biologia'), ('geo', 'Geografia'), ('inf', 'Informatyka'), ('edb', 'Edukacja dla bezpieczeństwa'), ('prz', 'Wiedza o przedsiębiorczości'), ('w-f', 'Wychowanie Fizyczne'), ('rel', 'Religia / Etyka'), ('fil', 'Filozofia')], max_length=3)),
                ('lesson_day', models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek')], default=1)),
                ('lesson_order', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('group', models.BooleanField(default=False)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lessonplan')),
                ('classRoom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article')),
            ],
        ),
    ]
