# Generated by Django 4.0 on 2021-12-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lesson')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_teacher', to='backend.teacher')),
                ('unavailable_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_teacher', to='backend.teacher')),
            ],
        ),
    ]
