# Generated by Django 4.1.1 on 2022-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('s', 'Sport'), ('b', 'Biblioteka'), ('g', 'Strona główna'), ('k', 'Konkursy')], max_length=1),
        ),
    ]
