# Generated by Django 4.0 on 2021-12-19 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitution',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
