# Generated by Django 4.1.1 on 2022-10-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_category_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaysOff',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='className',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='substitute_teacher',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='unavailable_teacher',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonPlan',
        ),
        migrations.DeleteModel(
            name='Substitution',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
