# Generated by Django 4.1.1 on 2022-10-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_article_author_article_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('excel_file', models.FileField(upload_to='uploads/plans')),
            ],
        ),
    ]
