# Generated by Django 4.1.1 on 2022-10-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
