# Generated by Django 4.1.1 on 2022-10-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_article_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_task_status', 'x')]},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
