# Generated by Django 4.1.1 on 2022-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
